7 migrate UI to flowbite
llettieri/movies-series-lookup pull request #8
Opened 2024-08-26 18:06 UTC by llettieri

2024-09-04 19:36 UTC, nilshindermann requested changes
Some feedback / things to do:

- [x] Header links (brand + search) are non-`next/link` components
- [x] All card links are non-`next/link` components
- [x] Movie/Series title is always a link, even if it's href is empty
- [x] `Warning: Each child in a list should have a unique "key" prop.`
      I think this comes from `CreditsTable.tsx`

Please also fix the bugs you found yourself 😄

2024-09-08 15:52 UTC, llettieri commented on components/Footer.tsx
> +            </FooterLinkGroup>*/}
WIP: see ticket https://github.com/llettieri/movies-series-lookup/issues/5

2024-09-09 17:24 UTC, nilshindermann reviewed
Almost there 😉

2024-09-09 17:24 UTC, nilshindermann commented on .eslintrc.js
> +    ignorePatterns: ['manifest.ts']
Why is this needed?

2024-09-09 17:24 UTC, nilshindermann commented on components/CreditsTable.tsx
> +                                    key={`${p.id}_${Math.round(Math.random() * 1000)}`}
[I think this is bad practice](https://react.dev/learn/rendering-lists#where-to-get-your-key:~:text=Keys%20must%20not%20change%20or%20that%20defeats%20their%20purpose!%20Don%E2%80%99t%20generate%20them%20while%20rendering.)

2024-09-09 20:03 UTC, nilshindermann approved these changes
nice work! ❤️

2024-09-09 20:11 UTC, merged